### ISSUE TITLE
thread 模式下用户编写的代码无法收到 signal.SIGINT 信号

### ISSUE THREAD

**Issue by xdjiangyang** [filamoon/pyapollo#6]
我在用 pyapollo 的 thread 模式编写 demo 时，signal.SIGINT 信号被 self._signal_handler 收到，导致 demo 程序无法退出。可否让 ApolloClient 不响应 signal.SIGINT，signal.SIGTERM 和 signal.SIGABRT 信号，改由用户在退出函数中显示调用 stop() 函数。

**Comment by filamoon** [comment]
增加了一个 catch_signals 开关
